apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: hello-world
build:
  local:
    push: true
  tagPolicy:
    customTemplate:
      template: "dev-{{.USER}}-{{.INPUT_DIGEST}}"
      components:
        - name: USER
          envTemplate:
            template: "{{.USER}}"
        - name: INPUT_DIGEST
          inputDigest: { }
  artifacts:
    - image: docker.io/irvifa/skaffold-kpt-example
      jib: { }
      context: .
deploy:
  kubeContext: kind-kubernetes-days-id-demo
  kustomize:
    paths: [ "kubernetes/dev" ]
profiles:
  - name: prod
    deploy:
      kustomize:
        paths: [ "kubernetes/prod" ]
    patches:
      - op: replace
        path: /build/tagPolicy
        value:
          inputDigest: { }
  - name: latest
    patches:
      - op: replace
        path: /build/tagPolicy
        value:
          sha256: { }
