apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
        - name: skaffold-kpt-example
          image: docker.io/irvifa/skaffold-kpt-example
          args: [ 'server', '/etc/config/hello-world.yaml' ]
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 60
          volumeMounts:
            - name: hello-world-volume
              mountPath: /etc/config
      volumes:
        - name: hello-world-volume
          configMap:
            name: hello-world-config
