apiVersion: apps/v1
kind: Deployment
metadata:
  name: skaffold-kpt-example
spec:
  selector:
    matchLabels:
      app: skaffold-kpt-example
  template:
    metadata:
      labels:
        app: skaffold-kpt-example
    spec:
      containers:
        - name: skaffold-kpt-example
          image: docker.io/irvifa/skaffold-kpt-example
          args: ['server', '/etc/config/hello-world.yaml']
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /hello-world
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
          readinessProbe:
            httpGet:
              path: /hello-world
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 60
          volumeMounts:
            - name: hello-world-volume
              mountPath: /etc/config
      volumes:
        - name: hello-world-volume
          configMap:
            name: hello-world-config
